# Add this in your configuration.yaml and restart Home Assistant
rest_command:
  start_print:
    url: "http://192.168.1.110/printer/print/start"  # EDIT the ip with yours
    method: POST
    payload: '{"filename": "{{ payload_data }}"}'
    headers:
      Content-Type: application/json
  queue_job_print:
    url: "http://192.168.1.110/server/job_queue/job"
    method: POST
    payload: '{"filenames": "{{ payload_data }}"}'
    headers:
      Content-Type: application/json
  queue_start_print:
    url: "http://192.168.1.110/server/job_queue/start"
    method: POST
    headers:
      Content-Type: application/json
  queue_job_remove:
    url: "http://192.168.1.110/server/job_queue/job"
    method: DELETE
    payload: '{ "all": true }'
    headers:
      Content-Type: application/json
