type: custom:mini-graph-card
name: Bed
align_state: center
icon: mdi:thermometer-lines
hour24: true
hours_to_show: 2
points_per_hour: 60
show:
  labels: true
  fill: true
entities:
  - entity: sensor.printername_bed_temperature
    name: Bed
    color: green
